services:
  data-service:
    container_name: data-service-container
    image: data-service
    build:
      context: .
    ports:
      - "${APP_HOST_PORT}:8080"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 2s
      timeout: 10s
      retries: 3
