[project]
name = "data-service"
version = "0.1.0"
description = "Servicio que maneja la gestión de datos"
authors = [
    { name = "Agustín Altamirano", email = " aaltamirano@fi.uba.ar" },
    { name = "Gabriel Diem", email = "wdiem@fi.uba.ar" },
    { name = "Máximo Gismondi", email = "magismondi@fi.uba.ar" },
    { name = "Matías Valeriani", email = "mvaleriani@fi.uba.ar" },
]
requires-python = ">=3.13,<4.0"

[tool.poetry]
packages = [{ include = "src" }]
package-mode = false

[tool.poetry.dependencies]
fastapi = "^0.128.4"
newrelic = "^11.4.0"
uvicorn = "^0.40.0"
python-dotenv = "^1.2.1"
httpx = "^0.28.1"
pydantic = "^2.12.5"
aioboto3 = "^15.5.0"
uvloop = "^0.22.1"
redis = { version = "^7.1.0", extras = ["hiredis"] }
pillow = "^12.1.1"

[tool.poetry.group.dev.dependencies]
pytest = "^9.0.2"
pytest-cov = "^7.0.0"
pytest-socket = "^0.7.0"
pytest-asyncio = "^1.3.0"
pre-commit = "^4.5.1"
pylint = "^4.0.4"
mypy = "^1.19.1"
black = "^26.1.0"
types-aioboto3 = "^15.5.0"
types-aiobotocore-s3 = "^3.2.0"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
pythonpath = ["src"]
addopts = "--disable-socket --allow-hosts=127.0.0.1"

[tool.pylint.main]
init-hook = "import sys; sys.path.insert(0, 'src')"

[tool.pylint.similarities]
min-similarity-lines = 8

[tool.pylint.design]
max-attributes = 10
max-args = 10
max-positional-arguments = 8
max-locals = 20

[[tool.mypy.overrides]]
module = "newrelic.*"
ignore_missing_imports = true
